### ISSUE TITLE
Powertraintől kapott packet értékek felhasználása a műszerfalon.

### ISSUE THREAD

**Issue by bench1947** [SzFMV2018-Tavasz/AutomatedCar#143]

**Comment by bench1947** [comment]
@SzFMV2018-Tavasz/team5 Helló! Látom már megvan nektek a powertrain packet-je. Ezt majd valamikor be tudnátok rakni masterba? Köszönöm előre is!

**Comment by vroba** [comment]
Hali, igen már van róla [PR](https://github.com/SzFMV2018-Tavasz/AutomatedCar/pull/198), de @pintergreg azt írta itt, hogy:

> Köszönöm, hogy megcsináltad az exception-t, viszont úgy döntöttem, hogy egyelőre mégsem merge-elem a masterbe ezt a branchet, mert nem látom garantáltnak, hogy ez másnak nem tör-e meg valamit (pl. #213).
A team3 PR-jét még mindig nem fogadtam el, emiatt sem vagyok benne biztos, hogy ezt jó ötlet befogadni. Ez viszont nem a ti részetekről hiba.

Egyelőre várakozás van.

**Comment by Modizoli** [comment]
Ez már reviewra vár? @bench1947

**Comment by bench1947** [comment]
Igen: #256
