### ISSUE TITLE
Autó forgatásának referencia pontja

### ISSUE THREAD

**Issue by markkurucz** [SzFMV2018-Tavasz/AutomatedCar#188]
@SzFMV2018-Tavasz/team2 
@SzFMV2018-Tavasz/team6 
https://github.com/SzFMV2018-Tavasz/AutomatedCar/issues/22#issuecomment-367081212

Forgatással kapcsolatban szeretném ha megbeszélnénk hogy legyen.

wikiből másolva:

Egy-egy objektum leírása a következőképpen néz ki:

``` xml
<Object type="road_2lane_straight">
      <Position x="1700" y="144"/>
      <Transform m11="0" m12="1" m21="-1" m22="0"/>
      <Parameter name="roadpainting_1" value="1"/>
      <Parameter name="roadpainting_2" value="1"/>
      <Parameter name="roadpainting_3" value="1"/>
</Object>
```

* A `type` attribútum írja le, hogy milyen objektumról van szó. A példában egy 2 sávos egyenes útszakaszról.
* A `Position` elem megadja az elem viszonyítási pontjának koordinátáját.
* A `Transform` elem egy 2×2-es transzformációs mátrix, amely forgatást ír le.
* A `roadpainting` megadná, hogy milyen felfestések vannak vannak az úton, de ez nem releváns
* Egy ilyen egyenes útelem 350×350px, ekkora a kép is és ennek kell lennie az XML-ben is.

<details> <summary>Az út elemek viszonyítási pontjai</summary>

![](https://raw.githubusercontent.com/SzFMV2018-Tavasz/documentation/master/90right.png) ![](https://raw.githubusercontent.com/SzFMV2018-Tavasz/documentation/master/90left.png) 

![](https://raw.githubusercontent.com/SzFMV2018-Tavasz/documentation/master/45right.png) ![](https://raw.githubusercontent.com/SzFMV2018-Tavasz/documentation/master/45left.png)

![](https://raw.githubusercontent.com/SzFMV2018-Tavasz/documentation/master/6right.png) ![](https://raw.githubusercontent.com/SzFMV2018-Tavasz/documentation/master/6left.png)

![](https://raw.githubusercontent.com/SzFMV2018-Tavasz/documentation/master/tjunctionright.png)
![](https://raw.githubusercontent.com/SzFMV2018-Tavasz/documentation/master/tjunctionleft.png)

![](https://raw.githubusercontent.com/SzFMV2018-Tavasz/documentation/master/straight.png)
![](https://raw.githubusercontent.com/SzFMV2018-Tavasz/documentation/master/rotary.png)

![2_crossroad_1](https://raw.githubusercontent.com/SzFMV2018-Tavasz/documentation/master/2_crossroad_1.png)
![2_crossroad_2](https://raw.githubusercontent.com/SzFMV2018-Tavasz/documentation/master/2_crossroad_2.png)
</details><br>
Minden itt fel nem sorolt esetben feltételezhető, hogy a bal felső sarok a viszonyítási pont.

A mozgatásra szoruló elemek (vezérelt autó és NPC autók) nem képezik részét a világ leírásának, viszonyítási pontjuk nem definiált. A rendelkezésre bocsátott autó képek méretarányosak az összes többi objektummal. referenciapontnak célszerű a bal felső sarkot választani.

**Itt végül minden útelemnek a piros négyzet adja meg, hogy az lesz a forgatás középpontja?**
**Az autó elforgatását mi az autó képének középpontja körül gondoltuk, akkor annyi lenne a dolog hogy mint az útnál, itt is megadni a "piros négyzet helyét"?**

Írjatok srácok, beszéljük át ezt

**Comment by alberthajdu15** [comment]
Jelenleg van egy CarPacket amelyben található x, y, rotationPoint, rotation változók.
Az x, y a kirajzoláshoz szükséges pont amely a kép bal felső pontja.
A rotationPoint az a pont amely körül a forgatás történik, ez az autó középpontja.
A rotation pedig az elforgatás mértéke radiánban.

**Comment by markkurucz** [comment]
@SzFMV2018-Tavasz/team2 srácok? @SiposGergo

**Comment by SiposGergo** [comment]
@markkurucz 
Bocsi, próbáltam megbeszélni a csapattal, de nem annyira elérhetőek.
Szóval elvileg a piros pont az egy ilyen offset értéked ad meg, az elem elhelyezéséhez, de a forgatás minden esetben a bal felső sarok körül történik @csabalint-nak így sikerült helyesen kirajzolni a világot.

@alberthajdu15 
Szerintem így jó lesz nekünk, ahogy írod. A rotationPoint változó az autó bal felső sarkához képest relatív koordinátát ad meg, tehát a középpontját magának a képnek? 

Ugye ez az egész csak az általunk vezérelt autóra áll fent, hogy a vfb-ről lekérjük ezeket az adatokat a CarPacket-tel. Az általunk vezérelt autó mint AutomatedCar objektum megtalálható lesz a WordObjects tömbben? Mert most ugye a Main metódusban belekerül egy darab autó: 

` AutomatedCar car = new AutomatedCar(20, 20, "car_2_white.png");
w.addObjectToWorld(car);`

Én úgy gondolom ez egy NPC autó lesz majd aminek majd megírjátok a mozgását, hogy menjen körbe-körbe, amit most a jobbra csúszás szimulál. Viszont az általunk irányított autó akkor nem lesz benne a WordObject listában ugye?

**Comment by alberthajdu15** [comment]
@SiposGergo
Igen a rotationPoint az autó középpontja. 
Az hogy nektek hogy egyszerűbb megoldani a kamera helyes mozgatást azt szerintem döntsétek ti el. De ha megtudjátok így oldani akkor legyen ez: lesz két autó, az AutomatedCar ami nem lesz benne a WorldObjectsbe és ennek kirajzolási adatait a CarPacketből olvassátok. A másik autó pedig benne lesz a WordObjectsbe és annak külön mozgás metódust írunk.

**Comment by SiposGergo** [comment]
@alberthajdu15 
Rendben, szerinte így meg tudjuk oldani.

**Comment by markkurucz** [comment]
NPC autókból több is lehet majd egyébként. Az NPC autók is forgatás szempontjából ugyanígy kell majd működjenek mint az AutomatedCar, ők annyiban különböznek hogy előre definiált útvonalon haladnak. Az AutomatedCar-nak akkor lesz ez a rotationPoint-ja ami körül kell forgatni, illetve az NPC car-oknak is ugyanez a forgatási középpontjuk. Az NPC autókat xml-ben kell definiálnunk, hogy bekerüljön a wordObjects-be. Ez a vizualizáció szempontjából ugyanúgy AutomatedCar class lesz. Az xml-be bekerül még az útvonal is amin végig haladnak az NPC autók.
@alberthajdu15 @SiposGergo mi a véleményetek erről?

@csabalint mire való ez az offset pontosan, mit csináltok vele, mire használatos?

**Comment by balintbekefi** [comment]
Jelenleg a `resources` mappában van egy `reference_points.xml` nevű file, amiben ilyen jellegű entry-k vannak:

```
<Image name="utelem_neve.png">
		<Refpoint x="000" y="000"/>
</Image>
```

Ezek megfelelnek a "piros négyzet helyének" azoknál az útelemeknél, ahol az meg van adva - a leírásnak megfelelően ott, ahol nincs, a (0, 0) pontot tekintjük a forgatás referenciapontjának. Javítsatok ki, ha tévedek, de nekem egyelőre úgy tűnik, hogy egyszerűen az autókhoz tartozó képeket is hozzá kéne adni ehhez az XML-hez, meghatározva a közepük koordinátáját.

**Comment by markkurucz** [comment]
CourseDisplay.java
```java
private void drawWorldObject(WorldObject object, Graphics g, int offsetX, int offsetY) {
        BufferedImage image = null;
        // read file from resources
        try {
            image = ImageIO.read(new File(ClassLoader.getSystemResource(object.getImageFileName()).getFile()));
        } catch (IOException e) {
            LOGGER.error(e.getMessage());
        }

        /////////////////////
        Point center = referencePoints.getOrDefault(object.getImageFileName(), null);
        if (center == null) {
            center = new Point(0, 0);
        }
        ///////////////////


        AffineTransform at = new AffineTransform();
        at.scale(scale, scale);
        at.rotate(-object.getRotation(), object.getX(), object.getY());
        at.translate(object.getX() - center.x + offsetX, object.getY() - center.y + offsetY);

        ((Graphics2D) g).drawImage(image, at, this);
    }
```

A kódban is úgy van, hogyha nincs referencia pont, akkor a (0,0) lesz az. (//// jellel körbe vett rész).
Akkor jól gondoltam hogy a referencia pont a forgatás középpontja. Ha felvesszük az XML-be az autó képét akkor meg van a map-nak a kulcsa, és fogja tudna hogy milyen középpont körül forgassa. Kipróbálom

**Comment by markkurucz** [comment]
Végül, megnézve a DoD-ot sprint2 npc kocsik irányításával kapcsolatban, elég ha lesz egy NPC car.

**Comment by markkurucz** [comment]
@csabalint 👍 hozzáadva a ref xml-hez jól fordulunk

**Comment by markkurucz** [comment]
@balintbekefi 👍  Előzőt elírtam, neked akartam :D, azt hittem @csabalint válaszolt

Végül beírtuk az xml-be és így elfogadható lett, már csak megjelenítésben van probléma, itt a hozzákapcsolódó issue: #213 itt láttok gifeket hogy mi a helyzet
