### ISSUE TITLE
Autó kanyarodása és megjelenítés problémája

### ISSUE THREAD

**Issue by markkurucz** [SzFMV2018-Tavasz/AutomatedCar#213]
Mostmár az autó kanyarodása úgy tűnik jó, ehhez az kellett hogy a references.xml-be beírni a kocsi képének közzéppontját.

Viszont amit észrevettünk az az, hogy ha a balfelső útdarab képének széléhez ér a kocsi (mintha mikor a kamera követés következne) akkor elcsúszik minden teljesen más irányba, de amíg a négyzeten belül marad, addig jól fordul az autó.

Commit amire ez az egész vonatkozik: 4033b43 
tehát ezt ha checkoutoljátok akkor ugyanezeket kell kapjátok

## Ha az autó 10-el megy, és teljesen balra kormányoz (60fok balra)
![automatedcar_2_speed10_angle100](https://user-images.githubusercontent.com/9610727/37578722-f8978bf8-2b3a-11e8-881d-87a2605ecc59.gif)

## Ha az autó 10-el megy és teljesen jobbra kormányoz (-60fok)
![automatedcar_2_speed10_angle-100](https://user-images.githubusercontent.com/9610727/37578744-1289ddea-2b3b-11e8-9f10-72f9ff9a7d33.gif)

## Ha az autó 1-el megy és teljesen jobbra kormányoz (60fok)
Ennek pontosan az elején látszik hogy a középpontja körül forog megfelelően, ami alapvetően a bajunk volt. Viszont ez sem normális hogy középpont körül forog egyhelyben
![automatedcar_2_speed1_angle-100](https://user-images.githubusercontent.com/9610727/37578758-2357b0ca-2b3b-11e8-8869-d2ea9c292e44.gif)

## Nem kormányzunk  csak egyenesen megyünk 10-el
![automatedcar_2_speed10_angle0](https://user-images.githubusercontent.com/9610727/37578946-f92bffee-2b3b-11e8-96a0-8ef444cdd661.gif)

**Itt is úgy látszik hogy az autó csak akkor kezd el felfelé kilőni ha kiért az első útdarabból, vagy a kamerának kell elkezdenie követni**

Ezt kérlek nézzétek meg Ti is hogy miért lehet. @SzFMV2018-Tavasz/team2

**Comment by markkurucz** [comment]
@SzFMV2018-Tavasz/team2

**Comment by pintergreg** [comment]
@SzFMV2018-Tavasz/team6 Hadd kérdezzem már meg, hogy hogyan vezérlitek az autót?
A hajtáslánc elvileg még nincs a masterben, mivel gondok voltak azzal, hogy az input packet nem létezik náluk. Felmerült bennem, hogy olyan packetre várnak, ami nem fog megszületni, mert másikban van a szükséges infó. Vagy Ti hackkeltetek egy saját mozgatást magatoknak a teszteléshez.

**Comment by alberthajdu15** [comment]
@pintergreg
Én úgy tudom hogy csak meghatározott sebességgel és elfordulással van tesztelve amit belekódolunk. Nem hivatkozunk se a hajtásláncra, se az inputra.

**Comment by pintergreg** [comment]
@alberthajdu15 Értem, köszi!

**Comment by SiposGergo** [comment]
@markkurucz 
Foglalkozom a dologgal, jelenleg nem látom még az okát.
