### ISSUE TITLE
Ütközések detektálása és események kiváltása

### ISSUE THREAD

**Issue by D3mino** [SzFMV2018-Tavasz/AutomatedCar#217]

**Comment by vroba** [comment]
@D3mino: Szia, kész a statikus metódus, amivel lassítani tudod az autót (amikor táblának vagy NPC autónak megy)
Ezt kell csak hívnod:

```javascript
PowertrainSystem.carCollide();
```


#241 PR-t reviewold, ebben mergelném be a team5 branchbe és ha onnan mergeled a sajátodba már tudod is használni.
