### ISSUE TITLE
WorldObjectekre Shape-k illesztése

### ISSUE THREAD

**Issue by aauiwd** [SzFMV2018-Tavasz/AutomatedCar#221]
A pályán található objektumok reprezentálása alakzatokkal.

**Comment by aauiwd** [comment]
A Team1_WorldObjectShapeProject-ben már benne van egy kezdemény (Team1_Sprint2_#221 commit). Jelenleg minden objektumhoz egy téglalap tartozik, ami illeszkedik az objektumot reprezentáló képre.

**Comment by pintergreg** [comment]
A fa és a tábla egy különleges eset. A kép kiterjedése jóval nagyobb mint aminek neki lehet menni a felső nézet miatt: a lombkoronát látjuk.
Az a megoldást szeretném látni, hogy a képfájl középpontjától felvesztek egy mondjuk 15 sugarú kört és csak annak a körnek lehessen nekimenni. Tehát az autó négyzete ütközés nélkül érintheti a képfájl szélét (elmehet az ágak alatt) és konkrétan jó lenne ha elmenne alatta, tehát abban az esetben autó z-indexe (CSS kifejezéssel élve) alacsonyabb lenne. Ez a rész a @SzFMV2018-Tavasz/team2 -t is érinti

![tree_collidable](https://user-images.githubusercontent.com/3854784/37699220-d0d9c308-2ce6-11e8-9d84-78bf21200508.png)

A tábla majdnem ugyanaz (ráadásul nem is valósághű, hogy felfelé van fordítva), csak ott a sugár értelem szerűen kisebb kell legyen, én durván olyan 3px-t mondanék, amely 12 centi átmérőt jelentene elvileg, ami egészen reálisnak tűnik.

*Mindez lehet, hogy a kiírásból is egyértelmű volt, akkor nem kell vele különösebben foglalkozni.*

**Comment by aauiwd** [comment]
Értem, és köszönöm az útmutatást. 
Lenne egy további felmerülő kérdés, melyben szeretném, ha állást foglalnál:
Mi történjen a speciális útszakaszokkal, ahol a valós tartalom eltér a kép fizikai dimenziójától (kereszteződések, kanyarok)?

**Comment by pintergreg** [comment]
Ezen már gondolkodtam, az igazán szép megoldás az volna, ha a T elágazás pl. egy 8 pontból álló poligonnal volna reprezentálva, a kanyarok esetében az igazán szép megoldás az lenne, ha görbével lehetne leírni a szélét, de pillanatnyilag nem tudom, hogy az awt.shape eszközkészlete tud-e ilyet.

Lehet egy (közepesen durva) polygon közelítést használni minden kanyartípusra, pl. egy elég durva:
![90left_polygon](https://user-images.githubusercontent.com/3854784/37703218-3678bb16-2cf5-11e8-9fda-065b2adc19f2.png)
Az igazi kérdés az, hogy szükséges-e a nem ütközhető objektumokat így megcsinálni.
Ha az utakat szépen megoldjátok, az nagyon megkönnyíti a sávtartó implementálását a 3. sprintben valamelyik (még nincsenek szétosztva) csapatnak.

**Comment by pintergreg** [comment]
Nyilvánvaló, hogy ezeket a poligonokat is forgatni kell az adott elfogatási szöggel, de mivel ez az az autónál (és a szenzor háromszögeknél) mindenképpen kell, hogy menjen, gondolom nem újdonság.

**Comment by pintergreg** [comment]
Jelen sprintben ez a kérdés a @SzFMV2018-Tavasz/team2 -t érdekelheti, mivel nekik meg kell tudni határozni a sávokat.

**Comment by aauiwd** [comment]
Sok szép dolgot lehetne csinálni (Pl halmazműveletekkel előállíthatóak elemi alakzatokból is). A valódi kérdés, hogy ez elvárás-e. 
Bármelyik, megoldást is választjuk, ez nem kis munka, és rengeteg függősége van (például ezeket hatékonyan csak úgy lehetne ellenőrizni, ha a program debug üzemmódban a Shapeket is kirajzolná). 
Ha neked megfelel, akkor a javaslatom az, hogy a fák és a táblák esetében járjunk el a fent leírtak szerint, minden más esetben meg maradjunk az egyszerű téglalapos közelítésnél. Későbbiekben ezt a döntést még felülvizsgálhatjuk.

**Comment by pintergreg** [comment]
@aauiwd Véleményem szerint sokkal egyszerűbb eleve felvenni egy megfelelő poligont mint halmazműveletekkel előállítani. Főleg, hogy Javáról beszélünk. A Python Shapely csomagjával pl. nagyon egyszerű amit mondasz (azt szoktam használni), de az awt.shape API-ja azért -lássuk be- mérföldekkel marad el attól.

Azért vontam be a @SzFMV2018-Tavasz/team2 mert egyrészt teljesen jó meglátás, hogy ki kellene tudni rajzolni. Mivel a „szép megoldás” nekik kedvezne, elvárható, hogy ők oldják meg a debug kirajzolást (ráadásul eleve ők csinálták a vizualizációt), ha nekik ez nem kell, akkor nem kell vele foglalkozni.
Ha jól tévedek, akkor eddig senki nem csinálta ezt így meg(, bár a sávtartó sem érte el sosem a teljesen elvárt szintet).
Nekem teljesen jó a téglalap, de azért ne felejtsd el, hogy azt se ártana valahogy ellenőrizni, hiszen kénytelen vagy forgatni: azt téglalappal sem lehet megúszni.

**Comment by aauiwd** [comment]
Én amiatt aggódtam, hogy a sávtartó majd kicsit rángatni fog, ha nem elég pontosan illesztjük a képekre a poligont, de ezek szerint ezt kicsit túldimenzionáltam. 
Sikerült felkeltened az érdeklődésemet annyira, hogy nekiugrok a poligonoknak. 
Malac módszerem van az ellenőrzésre (vállalhatatlan taknyolással ki tudom rajzolni az egyes alakzatokat), jelenleg a célnak megfelel.

**Comment by pintergreg** [comment]
A sávtartónak alapvetően (a valóságban) is van egy finom szinuszgörbe szerű mozgása a sávon belül, egyenes úton is. 90°-os kanyar bevételét pedig egyáltalán nem várjuk el! Alapvetően a 6°-os útkanyarulatokkal tervezzük tesztelni, de azzal is lehet, hogy az egyenes útszakaszon kis szögben a sávzáró felé van irányítva az autó.

A rángatás kis görbületű útszakaszokon biztos nem fog előjönni, ezzel nem lesz gond. :smile:
