### ISSUE TITLE
A váltó többet ugrik egy billentyűleütésre

### ISSUE THREAD

**Issue by pintergreg** [SzFMV2018-Tavasz/AutomatedCar#231]
Ugyan nem tartom lenyomva hosszú ideig (pl. másodpercek), de a ciklusunk 25-ször fut másodpercenként és simán lehet, hogy egy leütés nyomva tartása több ciklust is felölelhet.

**Comment by Gabo250** [comment]
@SiposGergo dehogy ugrik többet csak flashelsz te :D

**Comment by pintergreg** [comment]
A masteren már jónak tűnik.
