### ISSUE TITLE
Az autó nem mozog

### ISSUE THREAD

**Issue by pintergreg** [SzFMV2018-Tavasz/AutomatedCar#250]
A inputpacket feltöltésre kerül, a műszerfalon van ennek jele, de az autó nem mozdul meg.
A sebesség és a fordulatszám a műszerfalon sem jó.

A váltó jel végig megy, a gázpedál nem megy följebb 1%-nál #248 a fékpedál állása nem csökkenthető #249 , de attól tartok a sebesség adat visszaírás lesz a gond, mivel a műszerfal sem jelzi.

A @SzFMV2018-Tavasz/team5 -nek adtam a hibajegyet, de a @SzFMV2018-Tavasz/team3 , @SzFMV2018-Tavasz/team4,  @SzFMV2018-Tavasz/team6 is kövesse a történéseket.

**Comment by Gabo250** [comment]
@pintergreg 
A gaz meg fek inputot javitottam tegnap délután és jo volt nálam azt fel is pusholtam a integration branchre még tegnap

**Comment by pintergreg** [comment]
Azt láttam is pedig és benne van. Valóban jól működik, elnézést.

**Comment by bench1947** [comment]
A sebesség és fordulatszám jelenleg azért nem jelenik meg a műszerfalon, mert eddig még nem volt packet a powertraintől a masterben. Amint tudom pótlom.

**Comment by pintergreg** [comment]
Viszont a műszerfalon nincs sebesség és fordulatszám! Így a @SzFMV2018-Tavasz/team4 nézzen rá, át is tettem nekik a hibajegyet.

**Comment by vroba** [comment]
@pintergreg Nem látom a hibajegyet, mivel kapcsolatos?

**Comment by pintergreg** [comment]
Azóta kiderült, hogy rossz helyre címeztem. Le is zárom inkább.
