### ISSUE TITLE
Pedestrian should turn around when crossed the street

### ISSUE THREAD

**Issue by pintergreg** [SzFMV2018-Tavasz/AutomatedCar#270]
Rotate it by 180° when when he crossed the street.

**Comment by markkurucz** [comment]
- [ ] Annak ellenőrzése hogy forgatás hatására a gyalogos eltűnik-e a pályáról, mint előzőleg, ha probléma lép fel akkor a megjelenítő csapat értesítése

**Comment by alberthajdu15** [comment]
@markkurucz 
A team2 által javított megjelenítéssel már nem tűnik el a gyalogos a forgatás után.

**Comment by markkurucz** [comment]
Az Nice! :D
