### ISSUE TITLE
A különböző inputlehetőségek megjelenítése a műszerfalon

### ISSUE THREAD

**Issue by bench1947** [SzFMV2018-Tavasz/AutomatedCar#273]

**Comment by bench1947** [comment]
@SzFMV2018-Tavasz/team3 Helló! Le tudná majd valaki írni közületek hogy az egyes funkciókhoz milyen billentyűk tartoznak? Köszönöm előre is!

**Comment by pintergreg** [comment]
#64

**Comment by bench1947** [comment]
Köszönöm
