### ISSUE TITLE
NPC car számára, a pályát leíró XML feldolgozása és abból tömb előállítása amin végig tud menni majd. Előre meghatározott úton

### ISSUE THREAD

**Issue by markkurucz** [SzFMV2018-Tavasz/AutomatedCar#277]
A pályát leíró xml fájlból, az útdarabok megfelelő sorrendbe rendezése az alapján hogy milyen távol van az origótól. Ha két ugyanolyan távolra van 2 útdarab, akkor azt választjuk amelyik (0,0)-hoz képest jobbra van. Ennek feldolgozása után, egy Lista vissza adása amely worldobjecteket tartalmaz, amivel majd az NPC autó tud dolgozni.

**Comment by pintergreg** [comment]
XML-t semmiképpen sem kell feldolgoznotok, mivel a @SzFMV2018-Tavasz/team1 elvileg metette és előállít belőle egy „buta” XmlObjects listát. Ezen csak azokat az infókat tartalmazzák amik az xml-ben vannak. A pályakirajzolás is ebből dolgozik elvileg.
Ebből is már készíthető egy road szűrés. Ha a type mezó (String) „road” karakterlánccal kezdődik, akkor út.
Ne implementáljátok mégegyszer azt ami már megvan!

**Comment by pintergreg** [comment]
Ha meg rendes worldObject lista kéne, akkor főleg nem akarjatok ilyesmit implementálni, kérjetek egy metódust a @SzFMV2018-Tavasz/team1-től, aki ad egy worldObject listát, leválogatva az utakkal.

**Comment by markkurucz** [comment]
Köszi Gergő! Ezeket még átgondoljuk akkor.
