### ISSUE TITLE
Van olyan felbontás, aminél a Dashboard alján a koordináták már nem jelennek meg rendesen. Feljebb kéne tolni mindent egy pár pixellel.

### ISSUE THREAD

**Issue by bench1947** [SzFMV2018-Tavasz/AutomatedCar#390]

**Comment by pintergreg** [comment]
Ez hogy lehet? Az ablakméret fix, a dachboard jpanel fixed layout-ot használ, a betűméret sem lehetne dinamikus? :open_mouth: 
Mi ez a felbontás?

**Comment by bench1947** [comment]
Nálam így jelenik meg: https://i.imgur.com/vSRpQyc.png

Míg van, ahol így: https://i.imgur.com/be9ETQ3.png 

Azóta mint kiderült mindkét kép 1920x1080-as felbontásnál készült, úgyhogy gondolom az ablakmérettel van a gond. Korábban első sprintnél is volt hasonló probléma, amikor bent a kivetítőn teljesen szétcsúsztak a gombok, amik nálam jól jelentek meg.

**Comment by pintergreg** [comment]
Megvan: nézd az ablakdekorációt. Más a vastagsága. Én a tartalom méretét rögzítettem, de lehet, hogy valaki az ablak méretének gondolta.
![](https://raw.githubusercontent.com/SzFMV2018-Tavasz/documentation/master/gui_plan.png)
Ez nem a team4 hibája, maximum a @SzFMV2018-Tavasz/team2 -é, de az is lehet, hogy már a kezdetben kiadott kód is rosszul volt (nem emlékszem, hogy ezzel a kérdéssel én foglalkoztam-e).

Bugnak bug, de nem tartom 5-ös nehézségűnek, illetve magas prioritásúnak sem.

**Comment by bench1947** [comment]
Feljebb viszek majd mindent egy pár pixellel, és akkor jó kell legyen.
