### ISSUE TITLE
Reverse radar miscalculates the distance

### ISSUE THREAD

**Issue by pintergreg** [SzFMV2018-Tavasz/AutomatedCar#405]
> 20:10:34.543 [main] DEBUG hu.oe.nik.szfmv.automatedcar.systemcomponents.ReverseRadar - Gear state is: R
> 20:10:34.543 [main] DEBUG hu.oe.nik.szfmv.automatedcar.systemcomponents.ReverseRadar - Now the Reverse Radar activated: true
> 20:10:34.543 [main] DEBUG hu.oe.nik.szfmv.automatedcar.systemcomponents.ReverseRadar - [Object distance: 1.7976931348623157E308] and [Reverse Radar State is: OK]

The Object distance is not changing.
![kepernyokep_2018-05-02_20-12-17](https://user-images.githubusercontent.com/3854784/39541162-2a0edfe2-4e45-11e8-881c-e46327263be7.png)
![kepernyokep_2018-05-02_20-07-09](https://user-images.githubusercontent.com/3854784/39541161-29e30a0c-4e45-11e8-974d-5943333a416f.png)

@SzFMV2018-Tavasz/team4 @SzFMV2018-Tavasz/team5 
Based on current master.

**Comment by pintergreg** [comment]
@bench1947 Teljesen igazad van, kétszeresen is átsiklottam efelett. :open_mouth:

**Comment by vroba** [comment]
Sziasztok, irtam a PR-ben (azt hiszem) hogy csak előkészítettem a cuccot, de még nem számol sajnos. A kijelzes és a kalkuláció folyamatban, holnapra igyekszem pusholni.

**Comment by vroba** [comment]
@SzFMV2018-Tavasz/team4 segítenétek, hogy ne szenvedjek sokat, mely metódusaitokra gondoltatok? :)

**Comment by bench1947** [comment]
Az UltrasonicSensor osztályban van 3 metódus:
- Legközelebbi Collidable objektum meghatározása
- Legközelebbi Collidable objektum távolságának meghatározása(gondolom ez kell)
- Legközelebbi Collidable objektum kiterjedésének meghatározása

Az automated car-ból elérhető a 8 szenzor egy listában. Abból ha jól emlékszem a 2. és a 3. szenzor a két hátsó.

**Comment by vroba** [comment]
Igen, a 2. és 3. szenzor lesz az. Nagyon köszönöm, lesem!

**Comment by vroba** [comment]
Javítva lett, elvileg működik szépen. Remélem nemsokára bekerül a team branchbe és megy a PR a masterba. Köszi! 🍺
