### ISSUE TITLE
Kormány állásának értéke mi lesz? @Team4-el egyeztetni,

### ISSUE THREAD

**Issue by markkurucz** [SzFMV2018-Tavasz/AutomatedCar#51]
Milyen formában kapjuk meg? Vektor vagy mi

**Comment by Roltown** [comment]
A kormány állásának mértékét az inputtól kell megkapnotok, nem tőlünk. A HMI-ről való input elvileg egy elírás (illetve valószínüleg a virtuális buszon ott kell leolvasnotok). Rákérdeztem előadás után, és azt mondták, hogy a Műszerfalon csak megjelenítések vannak, mi nem küldünk tovább semmilyen paramétert másoknak. Az Inputos csapattal egyeztessetek. Ha megnézitek a függőségi gráfot, felénk nincsen semmilyen függőségetek.

**Comment by ravaszla** [comment]
@SzFMV2018-Tavasz/team3  FYI
