### ISSUE TITLE
Keréktengely középpontból kiinduló vektorok meghatározása

### ISSUE THREAD

**Issue by markkurucz** [SzFMV2018-Tavasz/AutomatedCar#56]
mekkora 1px -> hány méter, sebesség egység mennyi

**Comment by pintergreg** [comment]
FYI: [wiki/virtuális világ/méretarány](https://github.com/SzFMV2018-Tavasz/AutomatedCar/wiki/A-virtu%C3%A1lis-vil%C3%A1g#m%C3%A9retar%C3%A1ny)
