### ISSUE TITLE
A VirtualFunctionBus Signal változás esemény

### ISSUE THREAD

**Issue by Hakuhun** [SzFMV2018-Tavasz/AutomatedCar#59]
Kéne egy esemény a VirtualFunctionBus jelének változásáról.

Tickenként küld jelet a bus a többi egységnek/állítja be a jelét, vagy lesz egy OnSignalChange esemény, amire feliratkozva megkapja a többi modul az aktuális Jelet?

**Comment by pintergreg** [comment]
A masterbe tegnap felkerült módosítások már működő példát tartalmaznak a szignálküldő rendszerről.
A pusztán szemléltetésre szolgáló Driver osztály szignálokat küld, amelyet a PowertrainSystem elkap és megnöveli az autó X koordinátáját a szignálban hordozott értékkel.

Ehhez a szereplőknek meg kell valósítaniuk az ISystemComponent interfészt.
