### ISSUE TITLE
Hajtáslánc modell implementálása

### ISSUE THREAD

**Issue by Hakuhun** [SzFMV2018-Tavasz/AutomatedCar#60]
A Hajtáslánc modell alap implementációja.

A sebességet tároló mező
A sebességet visszaadó metódus

A sebességet változtató metódus sorozat 
és Input kezelés(fordulatszám, irány, pedál állás, stb.)

**Comment by vroba** [comment]
Team6-al utána még egyszer egyeztettünk, abban maradtunk hogy double-t kérnek és m/s -ban.

[https://github.com/SzFMV2018-Tavasz/AutomatedCar/issues/50](url)

> Arra gondoltunk akkor hogy, m/s ben kapjuk meg az erteket, ha tolatas tortenik akkor pedig negativ ertek:
Elore pl 50m/s
Hatra pl -20m/s

**Comment by vroba** [comment]
@Hakuhun 
Lehet nem a mi feladatunk a Fordulatszám output, mert a Team 4 User story 1-ben úgy látom, hogy náluk output:

[https://github.com/SzFMV2018-Tavasz/AutomatedCar/issues/65](url)

**Comment by pintergreg** [comment]
@vroba Rosszul linkelted az issue-kat. `#65` így megérti a github és linket csinál belőle. Szerkesztettem a hosszászólásaidat.

A műszarfal _csak kijelez_! Ti számoljátok ki a fordulatszámot, hiszen a hajtásláncnak ez része (a belső váltó fokozatoknál kell - lásd lentebbi megjegyzés). A Team4 esetében azt jelenti, hogy output, hogy ki kell rajzolni. Nálatok azt, hogy ki kell számolni. A nálatok kiszámolt fordulatszám( és sebesség) bemenete a műszarfalnak, amit ők egy „analóg óraként” kirajzolnak.

* azt a megoldást szoktál választani a hajtáslánc esetében, hogy belső váltó fokozatként definiálnak 1-es, 2-es, 3-as stb. fokozatot, de ez csak belső állapot, kifelé PRND van, ezek a D-n belül vannak, a gyorsítás leprogramozásához kellenek csupán.

**Comment by Hakuhun** [comment]
Szerintem jó. :D

Szerintem setterek nem kellenek, mert a rendszeren kívűl nem befolyásolatja semmi a sebességet és a fordulatszámot.

**Comment by vroba** [comment]
Javítottam a 35d74b8 commitban.

**Comment by vroba** [comment]
Kész
