### ISSUE TITLE
Auto modell implementálása

### ISSUE THREAD

**Issue by vroba** [SzFMV2018-Tavasz/AutomatedCar#70]

**Comment by Hakuhun** [comment]
Az auto modell megegyezik a Hajtáslánc modellel #60  , vagy ez egy teljesen másik része a feladatnak?

**Comment by vroba** [comment]
Gondoltam az autó tulajdonságainak lesz egy osztály, de inkább foglalja magába a hajtáslánc modell, ne bonyolítsuk.
