### ISSUE TITLE
Interface létrehozása Input-csapattal kormány-, váltó-, ACC-, gáz-, és fékállás, lanekeeping és parking állapotok átvételére

### ISSUE THREAD

**Issue by bench1947** [SzFMV2018-Tavasz/AutomatedCar#73]

**Comment by bench1947** [comment]
@SzFMV2018-Tavasz/team3 Helló!

Tisztázás érdekében szeretném megkérdezni, hogy végül milyen típusú változók fogják tárolni ezeket az adatokat:

- kormányállás
- váltó (Kedden egy enum volt megemlítve. Ezt gondolom majd ti hozzátok létre. Hozzánk ez az enum típus mikor/hogyan fog átkerülni?)
- ACC céltávolság és célsebesség
- lane keeping, parking pilot (Ezek gondolom bool típus lesznek.)
- irányjelző
- gáz (Kedden 0-100 int volt említve, ez nekünk is tökéletes)
- fék (Kedden 0-100 int volt említve, ez nekünk is tökéletes)

**Comment by Gabo250** [comment]
kormányállás - szögben lesz megadva(feltételezzük, hogy csak egyszer fordulhat 360 fokot)
váltó - ahogy le lett nyomva a váltó gomb úgy értesíteni fog titeket róla (event formájában vagy bármi)
ACC - int típusu(szerintem az  a legegyszerűbb)
lane keeping, parking pilot - igen ez egy bool tipusú változóban fog tárolodni, hogy be vab-e kapcsolva
irányjelző - egy leftindex-rightindex tipusú bool változóban szerintem tökéletes

**Comment by Skori** [comment]
Az ACC esetén a cél sebesség 30-160-ig terjedő int lesz.
Viszont a céltávolság inkább enum lesz 0.8/1/1.2/1.4 -os értékekkel.

**Comment by bench1947** [comment]
Konkrétan milyen típusban lesz megadva a kormányállás? Int? Lehet negatív is?

**Comment by Gabo250** [comment]
@bench1947 
Szerintem egy [0;360] int lesz ahol 0 az alaphelyzet és a  360 a teljesen elfordult állapot

**Comment by Skori** [comment]
Nem a kormány -100-tól +100-ig terjedő doubel típus lesz. Ahol a 0 az egyenes a -100 a száz százalékok balra kitérés a +100 pedig a száz százalékok jobbra kitérés (ezt beszéltük órán is).

**Comment by pintergreg** [comment]
Nekem úgy rémlik, hogy @ravaszla azt javasolta, hogy a kormány is 0-100 legyen (egyik és másik irányban, tehát -100;100) mikor arról volt szó, hogy hány fokos kormánykerék elforgatás hány fokos kerék elforgatást eredményezzen. Ennek előnye, hogy a kormánykerék elfogatással nem kell foglalkozni, csak, hogy mennyire van elforgatva. Ezt a @SzFMV2018-Tavasz/team6 meg százalékos érték révén könnyen le tudja képezni kerékelforgatásra.

**Comment by rpetice** [comment]
Elojeles integer szerintem is. Az elfordulas aranya valoszinuleg nem 1:1
lesz, mert 100 fokot nem nagyon fordul a kerek. A kormany kb. 1.5 kort tesz
0 fokrol a lockig. (bar azt nem tudom, h mi csinaljuk-e.
szoval kerek: +/- 100 * 0.8 kb (double)
kormany: +/- 100 * 1.5 (int)

Szerintem! :)

2018. március 3. 13:30 Gergő Pintér írta, <notifications@github.com>:

**Comment by markkurucz** [comment]
A 6-os csapat akkor `double[-100;100]` -ként kezeli az implementálásnál a kormány elfordulásának mértékét százalékban. A negatív szám a balra való fordítást jelenti. Amíg nyomva tartja a bal vagy jobb gombot, akkor valamennyivel a megfelelő irányba ad hozzá egy megadott értéket folyamatosan. Pl. +0.2 ha jobbra fordítja épp.

**Comment by bench1947** [comment]
@SzFMV2018-Tavasz/team3 Az ACC céltávolság nem lehet enum, mivel nem tudunk double-t tárolni enumban. Stringként tárolva meg szerintem csak nehezítené mindenkinek a dolgát. Létre kellett hoznom az interface-t, mert a megjelenítéshez kell. Abban egyelőre double-ként kezeljük.

**Comment by pintergreg** [comment]
@bench1947 Bevallom nem próbáltam ki, de a lentebbi bolygós példában úgy látom tárol double-t az enumban.
https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html

**Comment by bench1947** [comment]
Valóban lehetséges, kipróbáltam. Nem tudtam hogy Javában lehetnek változók/metódusok egy enumban. Akkor így tárgytalan amit írtam, elnézést.
