### ISSUE TITLE
Műszerfal megjelenítéséhez szükséges felépítés elkészítése

### ISSUE THREAD

**Issue by bench1947** [SzFMV2018-Tavasz/AutomatedCar#76]
- [x] Dashboard osztály inicializálása a konstruktorban, mely kirajzolja az elemeket a megfelelő pozícióba.
- [x] Dashboard osztály frissítése egy UpdateDisplayedValues metódussal, melynek hívásakor az összes kirajzolt elem értéke frissül.
- [x] DashboardDisplaySystem SystemComponent leszármazott elkészítése, mely a Dashboard osztálynak szolgáltatja az adatokat, illetve loop-ban meghívja az UpdateDisplayedValues metódust.

**Comment by bench1947** [comment]
- [ ] Dashboard osztály inicializálása a konstruktorban, mely kirajzolja az elemeket a megfelelő pozícióba.
- [ ] Dashboard osztály frissítése egy UpdateDashboard metódussal, melynek hívásakor az összes kirajzolt elem értéke frissül.
- [ ] Hmi SystemComponent leszármazott elkészítése, mely a Dashboard osztálynak szolgáltatja az adatokat, illetve loop-ban meghívja az UpdateDashboard metódust.

**Comment by bench1947** [comment]
@pintergreg @usanyo Egy kis magyarázatot szeretnék kérni a packet-ek használatához. Ha készítek egy saját SystemComponent leszármazottat, hogy loopban frissítsem a műszerfal által kiírt értékeket, akkor a kell csinálnom egy saját packet osztályt is, vagy a szükséges információkat valaki másnak a packet-jéből fogom kinyerni?

**Comment by pintergreg** [comment]
@bench1947 Hirtelen átgondolva úgy látom, hogy a műszerfal csak elkap csomagokat, hiszen ti csak megjelenítetek adatokat. A pedálállás például a input csapattól jön, nekik kell egy brakePedalPacket-et, amit kiküldenek. Ezt aztán a hajtáslánc majd ti kapjátok el (ők számolnak vele ti, csak beállítjátok a progressbar értékét az alapján).

A hajtáslánc, ha már itt tartunk, kell, hogy definiáljon egy fordulatszám csomagot, aminek értéke függ a kapott gázpedál értékétől és a fordulatszám csomagot ki is kell küldeni, de ti azt újfent csak elkapjátok.

Pillanatnyilag nem jut eszembe olyan részfeladat, ami miatt nektek definiálni kellene csomagot, viszont meg kell egyeznetek az adatforrásként fellépő csapatokkal, hogy mik legyenek ezek a packetek (név, tartalom). Adott esetben ha nálatok már látszanak a dolgok, akkor lehet azt mondani, hogy így és így legyen...

**Comment by bench1947** [comment]
Így érthető. Köszönöm!
